adp_frontend:
    resource: "@AdpFrontendBundle/Controller/"
    type:     annotation
    prefix:   /

adp_backend:
    resource: "@AdpBackendBundle/Controller/"
    type:     annotation
    prefix:   /back

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"